:Buyer: as BU
:Sales Agent: as SA
:Purchasing Manager: as PM
:Warehouse Worker: as WW
:Purchasing Agent: as PA
:Accountant: as AC
:Drone: as DR
:Location: as LO

BU -> (Makes Order)
(Makes Order) -> SA
SA --> (Query for Inventory)
SA --> (Make Order)
(Make Order) --> WW
WW --> (Get Inventory)
SA --> (Request Inventory)
(Request Inventory) --> PA

WW --> (Assign Pallet)
(Assign Pallet) --> DR
DR --> (Move Pallet)
(Move Pallet) --> Location
Location --> (Send Notification)
